export const mockSearchResults = [
  {
    id: "1",
    name: "Sarah Johnson",
    title: "Founder & CEO",
    company: "TechVision Labs",
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330",
    insights: [
      "Founded 2 successful startups",
      "Based in New York",
      "500+ connections",
    ],
    isVerified: true,
  },
  {
    id: "2",
    name: "Michael Chen",
    title: "Co-founder",
    company: "InnovateLab",
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e",
    insights: ["AI/ML Expert", "Series A Funding", "Tech Mentor"],
    isVerified: true,
  },
  {
    id: "2",
    name: "Michael Chen",
    title: "Co-founder",
    company: "InnovateLab",
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e",
    insights: ["AI/ML Expert", "Series A Funding", "Tech Mentor"],
    isVerified: true,
  },
  {
    id: "2",
    name: "Michael Chen",
    title: "Co-founder",
    company: "InnovateLab",
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e",
    insights: ["AI/ML Expert", "Series A Funding", "Tech Mentor"],
    isVerified: true,
  },
  {
    id: "2",
    name: "Michael Chen",
    title: "Co-founder",
    company: "InnovateLab",
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e",
    insights: ["AI/ML Expert", "Series A Funding", "Tech Mentor"],
    isVerified: true,
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    title: "Founder",
    company: "GreenTech Solutions",
    imageUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80",
    insights: [
      "Sustainable Tech Pioneer",
      "Y Combinator Alumni",
      "Speaker at TechCrunch",
    ],
  },
];
